"on":
  push:
    branches:
    - master
name: Deploy to Porter
jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.3.4
    - name: Docker build, push
      id: docker_build_push
      run: |2

        export $(echo "${{secrets.ENV_TESTING_AGAIN}}" | xargs)
        echo "${{secrets.ENV_TESTING_AGAIN}}" > ./env_porter
        echo $TESTING
