"on":
  push:
    branches:
    - master
name: Deploy to Porter
jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.3.4
    - name: Testing
      id: testing
      run: |2

        export $(echo "${{secrets.ENV_UPDATE_GHA_TEST}}" | xargs)
        echo $TESTING_STAGING
